packages:
  - "packages/*"
  - "packages/build/infra"
  - "examples"
  - "apps/*"

allowBuilds:
  "@journeyapps/wa-sqlite": false
  dprint: false
  es5-ext: false
  esbuild: false
  msgpackr-extract: false
  playwright: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
  workerd: false

linkWorkspacePackages: true
verifyDepsBeforeRun: false
