packages:
  - "packages/*"
  - "packages/tsflows/infra"
  - "examples"

allowBuilds:
  dprint: false
  es5-ext: false
  esbuild: false
  msgpackr-extract: false
  unrs-resolver: false
  vue-demi: false

linkWorkspacePackages: true
