/**
 * Derives allocation scopes and run-local invocation keys.
 *
 * Ordinal step identity has three components: the kind of durable operation
 * (an activity dispatch or an internal engine operation), the stable
 * declaration identity (the activity name, or a fixed internal label), and an
 * optional explicit idempotency component — a caller-declared string or
 * object. Every ordinal counter in the engine
 * is keyed by the scope this module derives, and the scope is also folded
 * into the persisted key as `parentScope`, so two dispatches with distinct
 * declarations can never swap ordinals under a permuted fiber interleaving
 * (issues #73, #85, #98, #101).
 *
 * The derivation is injective: distinct `(kind, name, idempotency)` inputs
 * always produce distinct scopes. The name is length-prefixed so a name that
 * happens to contain the component separator cannot alias another
 * declaration, and both idempotency forms are canonicalized to a fixed-width
 * digest under distinct tags so a string can never alias the object identity
 * whose digest it happens to spell.
 *
 * Governing contract: `docs/specs/Concepts/Step Keys.md`.
 *
 * @since 0.1.0
 */
import { Sha256 } from "@smthrs/crypto"
import { Key, type Key as KeyType } from "@smthrs/keys"
import type * as Crypto from "effect/Crypto"
import * as Effect from "effect/Effect"
import * as Schema from "effect/Schema"

/**
 * Validates the engine-owned coordinates of a run-local invocation.
 *
 * @private
 * @since 0.1.0
 */
const Invocation = Schema.Struct({
  runId: Schema.NonEmptyString,
  parentScope: Schema.optionalKey(Schema.NonEmptyString),
  ordinal: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  tier: Schema.Literals(["compensable", "irreversible", "unsealed"])
})

/**
 * The declaration material an allocation scope is derived from.
 *
 * @since 0.1.0
 * @category models
 */
export interface AllocationIdentity {
  /**
   * `"activity"` for user-declared activity dispatches, `"internal"` for
   * engine-owned durable operations (queue offers, deferred tokens). The two
   * kinds own disjoint counter namespaces.
   */
  readonly kind: "activity" | "internal"
  /**
   * The stable declaration identity: an activity's declared name, or a fixed
   * label for an internal operation family. Diagnostic names must not be
   * passed here unless they are part of identity.
   */
  readonly name: string
  /**
   * The explicit idempotency component. A declared string and a declared
   * cache key input both refine the scope — two concurrent invocations of
   * one name with distinguishable inputs each own their own counter, so a
   * replay that reverses fiber-arrival order can never hand one invocation
   * the other's recorded outcome. Absent, invocations of one name share a
   * counter and remain allocation-ordered — indistinguishable declarations
   * have no material to order them by.
   */
  readonly idempotency?: string | Schema.JsonObject | undefined
}

/**
 * Derives the ordinal allocation scope of a durable operation.
 *
 * The scope keys the operation's ordinal counter and is folded into its
 * persisted invocation key as `parentScope`, so identity is stable
 * under any interleaving of distinct declarations.
 *
 * Injectivity: the name is length-prefixed (`<kind>/<length>:<name>`), so a
 * name containing `/s:` or `/c:` material cannot collide with a keyed form
 * of a shorter name, and the idempotency component is a fixed-shape tagged
 * digest appended after the name. Both idempotency forms canonicalize under
 * distinct one-character tags so a string can never alias the object identity
 * whose digest it happens to spell.
 *
 * The object form is caller-owned material, so it can carry values canonical
 * serialization rejects (`Date`, `undefined`, class instances, `Redacted`);
 * the failure surfaces as the typed `SchemaError` (issue #151), never
 * as a thrown defect. The string and absent forms
 * are total — the first overload keeps their error channel `never`.
 *
 * @since 0.1.0
 * @category derivations
 */
export const allocationScope = (
  identity: AllocationIdentity
): Effect.Effect<string, Schema.SchemaError, Crypto.Crypto> =>
  Effect.gen(function*() {
    const base = `${identity.kind}/${identity.name.length}:${identity.name}`
    if (identity.idempotency === undefined) return base
    if (typeof identity.idempotency === "string") {
      const digest = yield* Schema.decodeUnknownEffect(Sha256)(identity.idempotency)
      return `${base}/s:${digest}`
    }
    const key = yield* Schema.decodeUnknownEffect(Key)({ kind: "declaration", input: identity.idempotency })
    return `${base}/c:${key}`
  })

/**
 * Derives an invocation key from engine-generated input.
 *
 * The input is engine-generated by construction — a finite counter
 * ordinal, a literal tier, and plain string scopes — so canonical
 * serialization cannot reject it. A failure here is an engine defect, and it
 * surfaces as the typed `SchemaError` itself (issue #151) rather than
 * being discarded through `Result.getOrThrow`.
 *
 * @since 0.1.0
 * @category derivations
 */
export const invocationKey = (input: {
  readonly runId: string
  readonly parentScope?: string | undefined
  readonly ordinal: number
  readonly tier: "unsealed" | "compensable" | "irreversible"
}): Effect.Effect<KeyType, Schema.SchemaError, Crypto.Crypto> =>
  Schema.decodeUnknownEffect(Invocation)(input).pipe(
    Effect.flatMap((validated) => Schema.decodeUnknownEffect(Key)({ kind: "invocation", ...validated }))
  )
