/**
 * Generated artifacts maintained by an external generator subprocess.
 *
 * A generated artifact is a checked-in file some tool produces: smithers'
 * llms bundles, declaration files, and component-source doc pages, tevm's
 * barrel files and generated biome.json. This rule runs the generator as a
 * subprocess and applies the write/check/contract triad, promoted from
 * GithubCiGen to the whole catalog:
 *
 * - `write` runs the generator and lets it write its outputs. It is never
 *   cacheable: a replayed hit would report success for files that were never
 *   written.
 * - `check` snapshots the declared outputs, runs the generator, and compares
 *   what it wrote against the snapshot, applying every declared `normalize`
 *   rule to both sides first. With `restoreOnFailure` the snapshot is
 *   restored in a finally, so the tree ends byte-identical pass or fail, the
 *   property smithers' check-dts gate implements by hand. Without it a failed
 *   check leaves the regenerated output in place, where it is the fix.
 * - `contract` runs the generator in its own verifying form, selected through
 *   `args` (for example `--check`), and trusts its exit code. The generator
 *   must not write in this mode.
 *
 * In `contract` and `check` the declared outputs are also declared inputs, so
 * editing a generated file re-keys the target. This is the argument
 * GithubCiGen makes for the workflow file, generalised to every generator.
 *
 * @since 0.1.0
 */
import * as Effect from "effect/Effect"
import * as Schema from "effect/Schema"
import * as Input from "./Input.ts"
import * as Runtime from "./Runtime.ts"
import * as Target from "./Target.ts"
import * as ToolBuild from "./ToolBuild.ts"

/**
 * How a generated-artifact target treats its outputs.
 *
 * The constructor default is `check`: the non-mutating form is the safe
 * resolution for a declaration that does not say otherwise, and it is the
 * mode every drift gate wants. `write` is reached through the `build` verb;
 * the `lint` verb maps `write` to `check` so no lint or CI run mutates a
 * checked-in file.
 *
 * @category schemas
 * @since 0.1.0
 */
export const Mode = Schema.Literals(["contract", "check", "write"]).pipe(
  Schema.withConstructorDefault(Effect.succeed("check" as const))
)

/**
 * How a generated-artifact target treats its outputs.
 *
 * @category models
 * @since 0.1.0
 */
export type Mode = typeof Mode.Type

/**
 * A comparison normalization applied to both sides of a drift check.
 *
 * `strip-timestamps` replaces ISO 8601 calendar timestamps (a `YYYY-MM-DD`
 * date followed by a time, with optional seconds, fractional seconds, and
 * zone) with a fixed token before comparing. A generator that stamps the
 * current time into its output can never drift-check without it, because the
 * regenerated bytes always differ from the checked-in ones. The
 * normalization affects only the comparison: a restored snapshot keeps its
 * exact original bytes.
 *
 * @category schemas
 * @since 0.1.0
 */
export const Normalize = Schema.Literals(["strip-timestamps"])

/**
 * A comparison normalization applied to both sides of a drift check.
 *
 * @category models
 * @since 0.1.0
 */
export type Normalize = typeof Normalize.Type

/**
 * Attributes for {@link GeneratedArtifact}.
 *
 * `runtime` is the interpreter that runs the generator. `generator` is the
 * program it executes and `args` is its argument list. `srcs` is the
 * complete read set beyond the generator itself: every file the generator
 * reads is declared here, because only a declared read is key material.
 * `outputs` names the files the generator produces, relative to `cwd`.
 * `deps` carries the targets whose outputs the generator reads. `mode`
 * selects the write/check/contract behaviour and defaults to `check`.
 * `restoreOnFailure` snapshots the declared outputs before a `check` run and
 * restores them in a finally, so the tree ends byte-identical pass or fail.
 * `normalize` lists the comparison normalizations a `check` run applies.
 * `env` declares the environment the generator reads and is key material.
 * `cwd` is the workspace-relative directory the generator runs in and
 * defaults to the workspace root.
 *
 * @category schemas
 * @since 0.1.0
 */
export const Attrs = Schema.Struct({
  runtime: Runtime.Runtime,
  generator: Input.File,
  args: Schema.Array(Schema.String).pipe(
    Schema.withConstructorDefault(Effect.succeed([]))
  ),
  srcs: Schema.Array(Input.Declared),
  outputs: Schema.NonEmptyArray(Schema.NonEmptyString),
  mode: Mode,
  deps: Schema.Array(Target.Target).pipe(
    Schema.withConstructorDefault(Effect.succeed([]))
  ),
  restoreOnFailure: Schema.Boolean.pipe(
    Schema.withConstructorDefault(Effect.succeed(false))
  ),
  normalize: Schema.Array(Normalize).pipe(
    Schema.withConstructorDefault(Effect.succeed([]))
  ),
  env: Schema.Record(Schema.String, Schema.String).pipe(
    Schema.withConstructorDefault(Effect.succeed({}))
  ),
  cwd: Schema.NonEmptyString.pipe(
    Schema.withConstructorDefault(Effect.succeed("."))
  )
})

/**
 * Attributes for {@link GeneratedArtifact}.
 *
 * @category models
 * @since 0.1.0
 */
export type Attrs = typeof Attrs.Type

/**
 * The snapshot-regenerate-compare-restore program a `check` run spawns.
 *
 * The comparison runs inside the child process for two reasons. Plan nodes
 * form a serializable AST, so the snapshot bytes a pre-run step reads cannot
 * flow into the payload of a post-run step. And the executor's action layer
 * stack is fixed, so the sequence cannot be a new action. What can cross the
 * boundary is one inline program the shared exec action spawns, which is
 * what this is: the exec layer supplies confinement, the closed environment,
 * and bounded output capture, and this program supplies the drift verdict.
 *
 * The program reads its spec as JSON from the first argument, snapshots each
 * declared output relative to its working directory, runs the generator
 * under the same interpreter (`process.execPath`), compares the regenerated
 * outputs against the snapshot after applying the declared normalizations,
 * and exits non-zero on drift or generator failure. With `restore` set it
 * restores the snapshot in a finally: files the generator changed get their
 * original bytes back and files it created are removed, so the tree ends
 * byte-identical pass or fail. Only declared outputs are snapshotted and
 * restored; a generator that writes anything else in check mode leaves it
 * behind. Outputs are compared as UTF-8 text.
 *
 * The interpreter flag spelling comes from {@link Runtime.evaluate}. The
 * program is CommonJS, which `node -e` and `bun -e` both accept.
 */
const checkDriver = String.raw`"use strict"
const fs = require("node:fs")
const path = require("node:path")
const { spawnSync } = require("node:child_process")
const spec = JSON.parse(process.argv[1])
const timestamp = /\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2})?(\.\d{1,9})?(Z|[+-]\d{2}:?\d{2})?/g
const normalize = (text) =>
  spec.normalize.includes("strip-timestamps") ? text.replace(timestamp, "<timestamp>") : text
const snapshot = new Map()
for (const output of spec.outputs) {
  let content
  try {
    const stats = fs.lstatSync(output)
    if (stats.isFile()) content = fs.readFileSync(output, "utf8")
  } catch {
    // A missing or unreadable output snapshots as undefined and reads as drift.
  }
  snapshot.set(output, content)
}
const restore = () => {
  for (const [output, content] of snapshot) {
    try {
      if (content === undefined) {
        fs.rmSync(output, { force: true })
      } else {
        fs.mkdirSync(path.dirname(output), { recursive: true })
        fs.writeFileSync(output, content)
      }
    } catch (cause) {
      process.stderr.write(
        "generated-artifact: could not restore " + output + ": " + String(cause && cause.message || cause) + "\n"
      )
    }
  }
}
let code = 1
try {
  const run = spawnSync(process.execPath, [spec.generator, ...spec.args], { stdio: "inherit" })
  if (run.error) throw run.error
  code = run.status === null ? 1 : run.status
  if (code === 0) {
    const drifted = []
    for (const output of spec.outputs) {
      let after
      try {
        const stats = fs.lstatSync(output)
        if (stats.isFile()) after = fs.readFileSync(output, "utf8")
      } catch {
        // Treated as drift below.
      }
      const before = snapshot.get(output)
      if (before === undefined || after === undefined || normalize(before) !== normalize(after)) {
        drifted.push(output)
      }
    }
    if (drifted.length > 0) {
      process.stderr.write(
        "generated-artifact: generated output drifted: " + drifted.join(", ") +
          "; regenerate with the write half\n"
      )
      code = 1
    }
  }
} catch (cause) {
  process.stderr.write("generated-artifact: " + String(cause && cause.message || cause) + "\n")
  code = 1
} finally {
  if (spec.restore) restore()
}
process.exit(code)
`

/** The spec a `check` run hands the driver as one JSON argument. */
const checkSpec = (attrs: Attrs): string =>
  JSON.stringify({
    generator: attrs.generator.path,
    args: attrs.args,
    outputs: attrs.outputs,
    restore: attrs.restoreOnFailure,
    normalize: attrs.normalize
  })

/** Workspace-rooted notation for one path declared against `cwd`. */
const rootedPath = (cwd: string, path: string): string =>
  Input.resolvePath("", cwd === "." ? `//${path}` : `//${cwd}/${path}`)

/**
 * Runs an external generator subprocess and either writes its outputs or
 * drift-checks them.
 *
 * The plan records one tool run through {@link Target.runTool}, sequenced
 * before the shared output-capture step that digests every declared output
 * into the {@link ToolBuild.Outputs} success payload. In `contract` and
 * `write` modes the node runs the generator directly. In `check` mode it
 * runs the generator under the snapshot-compare-restore driver, and drift
 * surfaces as an exec failure in {@link ToolBuild.BuildError} whose stderr
 * names the drifted outputs.
 *
 * Only `contract` and `check` are cacheable, and in both the declared
 * outputs are declared inputs, so editing a generated file re-keys the
 * target. The `lint` verb maps `write` to `check` through `attrsForKind`, so
 * no lint or `ci` run mutates a checked-in file.
 *
 * Executing the plan requires the exec and output-capture layers, both part
 * of the executor's standard layer stack.
 *
 * @category targets
 * @since 0.1.0
 */
export const GeneratedArtifact = Target.make("GeneratedArtifact", {
  attrs: Attrs,
  kinds: ["build", "lint"],
  success: ToolBuild.Outputs,
  error: ToolBuild.BuildError,
  cache: (attrs) => attrs.mode !== "write",
  inputs: (attrs) =>
    attrs.mode === "write"
      ? []
      : attrs.outputs.map((output) => Input.file(`//${rootedPath(attrs.cwd, output)}`)),
  outputs: (attrs) => ({ cwd: attrs.cwd, paths: [...attrs.outputs] }),
  attrsForKind: (kind, attrs) =>
    kind === "lint" && attrs.mode === "write" ? { ...attrs, mode: "check" as const } : attrs,
  implementation: (attrs) =>
    ToolBuild.captureOutputs(
      Target.runTool({
        cwd: attrs.cwd,
        argv: attrs.mode === "check"
          ? Runtime.evaluate(attrs.runtime, checkDriver, [checkSpec(attrs)])
          : Runtime.run(attrs.runtime, [attrs.generator.path, ...attrs.args]),
        env: attrs.env
      }),
      attrs.cwd,
      [...attrs.outputs]
    )
})
