/**
 * The `node_modules` target.
 *
 * `node_modules` is not a special case of the build graph. It is a target,
 * produced by a target, keyed on declared content, and depended on by everything
 * that runs a workspace-installed tool.
 *
 * This replaces `PnpmWorkspace`, which was a manager-specific wrapper that
 * configured itself: it hardcoded pnpm, took the lockfile and workspace
 * manifest as attrs it did not use, and left the Install flow to discover the
 * manager through its own layer. One target now covers every manager, and the
 * manager arrives as a declaration the caller passes in.
 *
 * @since 0.1.0
 */
import { Install as InstallFlow, PackageManager as PackageManagerService } from "@smthrs/build"
import * as Effect from "effect/Effect"
import * as Schema from "effect/Schema"
import * as Input from "./Input.ts"
import * as PackageManager from "./PackageManager.ts"
import * as Target from "./Target.ts"

/**
 * Attributes for {@link Install}.
 *
 * `packageManager` is the declaration every other tool-running target also takes,
 * so one workspace value drives the install and every tool that resolves out of
 * the tree it produces.
 *
 * `lockfile` is a target rather than a file declaration: the lockfile is
 * generated by {@link Lockfile}, and depending on the target is what orders the
 * two. The lockfile's *content* still reaches this target's key, through the
 * `inputs` function below, so a hand-edited lockfile invalidates the install
 * even though the same file is another target's output.
 *
 * @category schemas
 * @since 0.1.0
 */
export const Attrs = Schema.Struct({
  packageManager: PackageManager.PackageManager,
  /**
   * The target that generates the lockfile, or `null` to use a checked-in one.
   *
   * @default null
   */
  lockfile: Schema.NullOr(Target.Target).pipe(
    Schema.withConstructorDefault(Effect.succeed(null))
  ),
  /** The root manifest target, when the manifest is generated. @default null */
  manifest: Schema.NullOr(Target.Target).pipe(
    Schema.withConstructorDefault(Effect.succeed(null))
  ),
  /** The workspace-definition target, when it is generated. @default null */
  workspace: Schema.NullOr(Target.Target).pipe(
    Schema.withConstructorDefault(Effect.succeed(null))
  ),
  /** The hand-written pnpm workspace definition and the manifests it selects. @default null */
  workspaceManifest: Schema.NullOr(Input.PnpmWorkspace).pipe(
    Schema.withConstructorDefault(Effect.succeed(null))
  )
})

/**
 * Attributes for {@link Install}.
 *
 * @category models
 * @since 0.1.0
 */
export type Attrs = typeof Attrs.Type

/**
 * The files an install is keyed on, whoever produced them.
 *
 * The lockfile pins every resolved version, `.npmrc` decides which registry and
 * which credentials the manager talks to, and the root manifest decides what the
 * workspace asked for. A change in any of the three changes what an install
 * produces, so all three are declared inputs.
 *
 * @category constructors
 * @since 0.1.0
 */
export const inputsFor = (attrs: Attrs): ReadonlyArray<Input.Declared> => [
  Input.file(PackageManager.lockfileName(attrs.packageManager)),
  Input.file(".npmrc"),
  Input.file("package.json"),
  ...(attrs.workspaceManifest === null ? [] : [attrs.workspaceManifest])
]

/**
 * Plans an install for the declared package manager.
 *
 * The wrapper target is not cacheable: a cache hit would report a link manifest
 * without restoring either the manager store or the `node_modules` tree it
 * describes. The nested flow's own steps are keyed for local freshness, which is
 * where skipping unchanged work belongs.
 *
 * @example
 * ```ts
 * import { Smithers } from "@smthrs/targets"
 *
 * const runtime = Smithers.Runtime.Node({ version: ">=22.19.0" })
 * const packageManager = Smithers.PackageManager.Pnpm({ version: "11.21.0", runtime })
 *
 * export const nodeModules = Smithers.Install({ packageManager })
 * ```
 *
 * @category targets
 * @since 0.1.0
 */
export const Install = Target.make("Install", {
  attrs: Attrs,
  kinds: ["run"],
  success: InstallFlow.LinkManifest,
  error: PackageManagerService.PackageManagerError,
  cache: false,
  inputs: inputsFor,
  implementation: (attrs) => InstallFlow.Install.call({ manager: attrs.packageManager.name })
})
