/**
 * The declarative automation rule and, above everything else, its
 * untrusted-input boundary.
 *
 * The refusal tests are the load-bearing ones. A renderer that quietly drops a
 * secret from an untrusted-input job, or renders one without its gate, ships a
 * workflow that reads like the declaration and behaves like a credential
 * handed to whoever opened the issue. Those cases are pinned here so the
 * boundary cannot be relaxed without deleting a test that says why.
 */
import * as Effect from "effect/Effect"
import * as Fs from "node:fs/promises"
import { tmpdir } from "node:os"
import * as NodePath from "node:path"
import { describe, expect, it } from "vitest"
import { checkGeneratedFile } from "../src/GeneratedFile.ts"
import {
  agent,
  Attrs,
  AutomationDeclarationError,
  GithubAutomation,
  markerHeader,
  outputPath,
  render,
  script,
  untrustedInputGate,
  UntrustedJobError,
  verb
} from "../src/GithubAutomation.ts"
import { parseWorkflow } from "../src/GithubWorkflow.ts"
import { Secret } from "../src/Secret.ts"
import * as Target from "../src/Target.ts"
import { packageManager } from "./toolchain.ts"

const workspaceRoot = NodePath.resolve(import.meta.dirname, "../../..")

const attrs = (overrides: Partial<Parameters<typeof Attrs.make>[0]> = {}): Attrs =>
  Attrs.make({
    slug: "issue-intake",
    target: "issueIntake",
    workflowName: "Issue intake",
    packageManager,
    on: { issues: ["opened"] },
    jobs: [agent({ id: "intake", entry: "intake.ts" })],
    ...overrides
  })

describe("render", () => {
  it("names the generating target in a marker header on the first line", () => {
    const rendered = render(attrs())
    expect(rendered.split("\n")[0]).toBe(
      "# GENERATED by //:issueIntake. Do not edit. Edit BUILD.ts and run smthrs run //:issueIntake."
    )
    expect(rendered.startsWith(markerHeader("issueIntake"))).toBe(true)
  })

  it("derives the output path from the slug", () => {
    expect(outputPath("issue-intake")).toBe(".github/workflows/gen.issue-intake.yml")
  })

  it("renders a workflow the repository's own reader parses", () => {
    const rendered = render(attrs({
      on: { issues: ["opened", "edited"], schedule: ["17 3 * * *"], workflowDispatch: true },
      concurrency: "gen-issue-intake-${{ github.event.issue.number }}",
      jobs: [
        agent({
          id: "intake",
          name: "decode and dedupe the report",
          entry: "intake.ts",
          permissions: { contents: "read", issues: "write" },
          secrets: [Secret("ANTHROPIC_API_KEY")]
        }),
        verb({ id: "gate", verb: "test", pattern: "//packages/...", needs: ["intake"] })
      ]
    }))
    const workflow = parseWorkflow(rendered)
    expect(workflow.name).toBe("Issue intake")
    expect(workflow.jobs.map((job) => job.id)).toEqual(["intake", "gate"])
    expect(rendered).toContain("ANTHROPIC_API_KEY: \"${{ secrets.ANTHROPIC_API_KEY }}\"")
    expect(rendered).toContain("node factory/automation/intake.ts")
    expect(rendered).toContain("pnpm exec smthrs test '//packages/...'")
  })

  it("renders a cache step for a trusted job", () => {
    const rendered = render(attrs({
      jobs: [agent({
        id: "review",
        entry: "review.ts",
        caches: [{ path: ".flows/pr-review", key: "k-${{ github.sha }}", restoreKeys: ["k-"] }]
      })]
    }))
    expect(rendered).toContain("uses: actions/cache@v4")
    expect(rendered).toContain("path: \".flows/pr-review\"")
    expect(rendered).toContain("restore-keys: k-")
  })

  it("renders no trailing whitespace and one trailing newline", () => {
    const rendered = render(attrs({
      jobs: [script({ id: "post", run: "echo one\n\necho two" })]
    }))
    expect(rendered.endsWith("\n")).toBe(true)
    expect(rendered.split("\n").some((line) => /\s$/.test(line))).toBe(false)
  })
})

describe("the untrusted-input boundary", () => {
  const sandbox = (overrides: Record<string, unknown> = {}) =>
    attrs({
      jobs: [
        script({
          id: "sandbox",
          untrustedInput: true,
          run: "node factory/automation/run-poc.ts",
          ...overrides
        })
      ]
    })

  it("refuses a declared secret on an untrusted-input job", () => {
    const declaration = sandbox({ secrets: [Secret("ANTHROPIC_API_KEY")] })
    expect(() => render(declaration)).toThrow(UntrustedJobError)
    try {
      render(declaration)
      expect.unreachable("the renderer accepted a secret in an untrusted-input job")
    } catch (cause) {
      expect((cause as UntrustedJobError)._tag).toBe("smithers-build/UntrustedJobError")
      expect((cause as UntrustedJobError).job).toBe("sandbox")
      expect((cause as UntrustedJobError).message).toContain("ANTHROPIC_API_KEY")
    }
  })

  it("refuses a secret reached through the job environment", () => {
    expect(() => render(sandbox({ env: { TOKEN: "${{ secrets.NODE_AUTH_TOKEN }}" } })))
      .toThrow(/reaches a credential through env.TOKEN/)
  })

  it("refuses a secret reached from the job script", () => {
    expect(() => render(sandbox({ run: "echo ${{ secrets.ANTHROPIC_API_KEY }}" })))
      .toThrow(/reaches a credential in its script/)
  })

  it("refuses the workflow token on an untrusted-input job", () => {
    expect(() => render(sandbox({ env: { GH_TOKEN: "${{ github.token }}" } })))
      .toThrow(/reaches a credential through env.GH_TOKEN/)
    expect(() => render(sandbox({ env: { TOKEN: "${{ secrets.GITHUB_TOKEN }}" } })))
      .toThrow(/reaches a credential through env.TOKEN/)
  })

  it("refuses a cache on an untrusted-input job", () => {
    expect(() => render(sandbox({ caches: [{ path: ".flows/x", key: "k" }] })))
      .toThrow(/a channel into the next run/)
  })

  it("refuses write permission on an untrusted-input job", () => {
    expect(() => render(sandbox({ permissions: { issues: "write" } })))
      .toThrow(/an untrusted-input job is read-only/)
  })

  it("forces the gate condition, read-only permissions, and a credential-free checkout", () => {
    const rendered = render(sandbox())
    expect(rendered).toContain(`    if: \${{ ${untrustedInputGate} }}`)
    expect(rendered).toContain("persist-credentials: \"false\"")
    const job = parseWorkflow(rendered).jobs.find((candidate) => candidate.id === "sandbox")
    expect(job?.condition).toContain("agent:approved")
    expect(job?.condition).toContain("OWNER")
    const body = rendered.slice(rendered.indexOf("  sandbox:"))
    expect(body).toContain("permissions:\n      contents: read")
    expect(body).not.toContain("secrets.")
  })

  it("ands a declared condition with the gate rather than replacing it", () => {
    const rendered = render(sandbox({ condition: "github.event.action == 'created'" }))
    expect(rendered).toContain(`if: \${{ (${untrustedInputGate}) && (github.event.action == 'created') }}`)
  })

  it("leaves a trusted job's secrets and permissions alone", () => {
    const rendered = render(attrs({
      jobs: [agent({
        id: "intake",
        entry: "intake.ts",
        permissions: { issues: "write" },
        secrets: [Secret("ANTHROPIC_API_KEY")]
      })]
    }))
    expect(rendered).toContain("issues: write")
    expect(rendered).toContain("ANTHROPIC_API_KEY: \"${{ secrets.ANTHROPIC_API_KEY }}\"")
    expect(parseWorkflow(rendered).jobs[0]?.condition).toBeUndefined()
  })
})

describe("declaration refusals", () => {
  it("refuses a workflow nothing would ever trigger", () => {
    expect(() => render(attrs({ on: {} }))).toThrow(AutomationDeclarationError)
  })

  it("refuses duplicate job ids and dangling needs", () => {
    expect(() => render(attrs({ jobs: [agent({ id: "a", entry: "one.ts" }), agent({ id: "a", entry: "two.ts" })] })))
      .toThrow(/duplicate job id/)
    expect(() => render(attrs({ jobs: [agent({ id: "a", entry: "one.ts", needs: ["b"] })] })))
      .toThrow(/which this workflow does not declare/)
  })

  it("refuses an entry that is not a file under factory/automation", () => {
    expect(() => render(attrs({ jobs: [agent({ id: "a", entry: "../../etc/passwd" })] })))
      .toThrow(/an entry is a lowercase "\.ts" file directly under factory\/automation/)
  })

  it("refuses a pattern outside the label grammar", () => {
    expect(() => render(attrs({ jobs: [verb({ id: "a", verb: "test", pattern: "--help" })] })))
      .toThrow(/is not a target pattern/)
  })

  it("refuses an unknown permission scope", () => {
    expect(() => render(attrs({ permissions: { packages: "write" } })))
      .toThrow(/is not one of actions, checks, contents, issues, pull-requests, statuses/)
  })
})

describe("GithubAutomation", () => {
  it("checks under build and lint and writes only under run", () => {
    const target = GithubAutomation(attrs())
    const metadata = Target.metadata(target)
    for (const kind of ["build", "lint"] as const) {
      expect((metadata.forKind(kind).attrs as Attrs).mode).toBe("check")
    }
    expect((metadata.forKind("run").attrs as Attrs).mode).toBe("write")
  })

  it("declares the generated file as an input in every checking verb", () => {
    const metadata = Target.metadata(GithubAutomation(attrs()))
    const paths = metadata.forKind("lint").inputs.map((input) => JSON.stringify(input))
    expect(paths.join(" ")).toContain(".github/workflows/gen.issue-intake.yml")
    expect(metadata.forKind("run").inputs.map((input) => JSON.stringify(input)).join(" "))
      .not.toContain(".github/workflows/gen.issue-intake.yml")
  })
})

describe("the drift gate", () => {
  it("passes on the rendered bytes and fails on a hand edit", async () => {
    const root = await Fs.mkdtemp(NodePath.join(await Fs.realpath(tmpdir()), "gen-automation-"))
    try {
      const declaration = attrs()
      const path = outputPath(declaration.slug)
      const contents = render(declaration)
      await Fs.mkdir(NodePath.join(root, ".github", "workflows"), { recursive: true })
      await Fs.writeFile(NodePath.join(root, path), contents, "utf8")
      await expect(Effect.runPromise(checkGeneratedFile(root, { path, contents }))).resolves.toBeUndefined()
      // The hand edit a drift gate exists to catch: a maintainer widens the
      // trigger in the generated file instead of in BUILD.ts.
      await Fs.writeFile(NodePath.join(root, path), contents.replace("types: [opened]", "types: [opened, edited]"))
      await expect(Effect.runPromise(checkGeneratedFile(root, { path, contents }))).rejects.toThrow(/drifted/)
    } finally {
      await Fs.rm(root, { recursive: true, force: true })
    }
  })
})

describe("the checked-in generated workflows", () => {
  it("all carry their marker header and parse", async () => {
    const directory = NodePath.join(workspaceRoot, ".github", "workflows")
    const names = (await Fs.readdir(directory)).filter((name) => name.startsWith("gen.") && name.endsWith(".yml"))
    expect(names.length).toBeGreaterThan(0)
    for (const name of names) {
      const source = await Fs.readFile(NodePath.join(directory, name), "utf8")
      expect(source, name).toMatch(
        /^# GENERATED by \/\/:[A-Za-z][A-Za-z0-9]*\. Do not edit\. Edit BUILD\.ts and run smthrs run \/\/:[A-Za-z][A-Za-z0-9]*\.\n/
      )
      expect(() => parseWorkflow(source), name).not.toThrow()
    }
  })
})
